### PR TITLE
fix: create job post service

### PR DESCRIPTION
**Pull request by uloamaka**
​
## Description

​Fixed the job service by moving the struct to the model file to maintain uniformity of code base.
[API DOCs LINK](https://staging.api-golang.boilerplate.hng.tech/api/docs/index.html#/) 

## Related Issue (Link to Github issue)

[​#54](https://github.com/hngprojects/hng_boilerplate_golang_web/issues/54)
## How Has This Been Tested?

​The test cover inputting the required data to create a job post, it passes as expected, add a new job into the db.

## Screenshots (if appropriate - Postman, etc):
​
Screenshot (364)

Screenshot (371)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Cyberguru1 — COMMENTED** [review]
please fix the service/jobpost folder package name

**Comment by uloamaka** [comment]
> please fix the service/jobpost folder package name

ok

**Comment by uloamaka** [comment]
> please fix the service/jobpost folder package name

done

**Review by Cyberguru1 — APPROVED** [review]
nice
all good

**Pull request merged**
