### PR TITLE
Feat: added get deleted newsletter emails

### PR DESCRIPTION
**Pull request by Ajinx1**
## Description

This pull request introduces a new API endpoint to retrieve soft-deleted newsletters.

### Key Features

* **Endpoint**: `GET /api/v1/newsletter-subscription/deleted`
* **Functionality**: Retrieves newsletters that have been soft-deleted.
* **Authentication**: Requires a valid JWT token for access.
* **Authorization**: Only users with the `SuperAdmin` role can access this endpoint.

[API DOC HERE](https://staging.api-golang.boilerplate.hng.tech/api/docs/index.html#/newsletter/get_newsletter_subscription_deleted)

### Acceptance Criteria

* The endpoint should accept HTTP GET requests.
* The request must include a valid authentication token in the Authorization header.
* The response should return a list of newsletters that have been marked as soft-deleted.

**Authorization Header**:
```json
{
    "Authorization": "Bearer <token>"
}
```

### Related Issue

This pull request addresses [Issue 288](https://github.com/hngprojects/hng_boilerplate_golang_web/issues/288).

### How Has This Been Tested?

The changes have been tested with the following methods:

* **Integration Tests**:
  * Verified successful retrieval of soft-deleted newsletters by an authorized SuperAdmin user.
  * Tested unauthorized access attempts with an invalid token.
  * Handled cases where a regular user attempts to access the endpoint without sufficient permissions.

### Screenshots (if appropriate - Postman, etc.)
image
image
image

### Types of Changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

* [x] My code follows the code style of this project.
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.

### CODE REVIEW

**Review by Micah-Shallom — DISMISSED** [review]
satisfactory implementation

**Review by Micah-Shallom — DISMISSED** [review]
satisfactory implementation

**Review by Micah-Shallom — DISMISSED** [review]
lgtm

**Review by Micah-Shallom — DISMISSED** [review]
lgtm

**Review by Cyberguru1 — DISMISSED** [review]

**Review by Cyberguru1 — APPROVED** [review]

**Review by Cyberguru1 — CHANGES_REQUESTED** [review]
please remove comments

**Comment by Ajinx1** [comment]
> please remove comments

done

**Review by Cyberguru1 — APPROVED** [review]

**Pull request merged**
